### ISSUE TITLE
define unmarshal behavior for invalid content

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#10]
Submitted by David Bau, entered by Joe Fialli.

Request is to define unmarshal behavior of invalid content when unmarshalling
validation is disabled.

Here is the exact content that is being requested to be defined by the
specification.
Extracted from JAXB 1.0 Specification, Section 2.1.2 Binding Framework, Ph 3

"How a JAXB technology implementation handles unmarshalling of an invalid
document when validation is disabled is implementation-specific. The same holds
true for marshalling an invalid content tree. It is expected that once an
implementation is aware that it cannot unambiguously complete unmarshalling or
marshalling, it will terminate processing with an exception."
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[1.0]

**Comment by lukasj** [comment]
defined in appendix B
