### ISSUE TITLE
mapping of property/field to xs:sequence - default order

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#13]
The JSR 222 EG already agreed that a mapping rule that maps the
Javabean like properties and fields within a class to a xs:sequence
compositor should be supported. However, the Javabean properties and
fields within a class are unordered. So should there be default order
specified ?

One suggestion was to use alphabetical order as default order.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
Default order has been defined to be _UNSPECIFIED_
