### ISSUE TITLE
Merge (original) XML Binding specification source

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jaxb-api#131]
Just an FYI...  The original (oracle) XML Binding specification source is now available via this CQ:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21466

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9.  Thanks!

**Comment by kwsutter** [comment]
Part of the overall Jakarta EE 9 Issue #122.

**Comment by lukasj** [comment]
fixed by #133
