### ISSUE TITLE
ContextFinder always load the JAXBContext from jaxb-runtime 2.3.3 

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jaxb-api#157]
After upgrading to jaxb-runtime 2.3.3, there is a new created provider file /META-INF/services/javax.xml.bind.JAXBContextFactory 
to load and create JAXBContext implementation, and this provider file doesn't exist in previous version like  jaxb-runtime-2.3.2 .  ContextFinder follows this order to discover the service implementation:
 ```
1. Provider of javax.xml.bind.JAXBContextFactory is loaded using the service-provider loading facilities, as defined by Java SE Platform, to attempt to locate and load an implementation of the service. 
2 . Look for resource /META-INF/services/javax.xml.bind.JAXBContext. If such a resource exists, its content is assumed to be the provider factory class.
```

As a consequence of this order,  The JAXBContex from jaxb-runtime 2.3.3 will be always loaded if there is jaxb-runtime 2.3.3 under server's common lib and jaxb-runtime 2.3.2 lib under /WEB-INF/lib. For the servlet container , load class with this order like what Tomcat does won't work anymore : 

-  Bootstrap classes of your JVM
-  ./WEB-INF/classes of your web application
- ./WEB-INF/lib/*.jar of your web application
-  System class loader classes 
-  Common class loader classes (server common lib)

**Comment by jimma** [comment]
@lukasj  @andymc12  Do you have any comments and thoughts about this issue ? Thanks.

**Comment by andymc12** [comment]
I'll defer to @lukasj, but it seems like a bug to me. I wonder if the new `META-INF/services/javax.xml.bind.JAXBContextFactory` was only intended for the 3.0 release (as `META-INF/services/jakarta.xml.bind.JAXBContextFactory`) and got into the 2.3.X stream by mistake.

I'm not positive, but I think this was the change that added it:
https://github.com/eclipse-ee4j/jaxb-ri/commit/76716e58851d2e0c5dde5b3a6551195adc812f72

**Comment by jimma** [comment]
@lukasj  Your thoughts ?

**Comment by lukasj** [comment]
Isn't this a problem of the particular implementation instead of API itself? Is there the same problem with com.sun.xml.bind:jaxb-runtime` artifact? In any case the look up algorithm can't be changed in 2.x versions. At least not till 3.0 gets out (simply because that is the version where the current focus is)

**Comment by jimma** [comment]
@lukasj  I thought fix this in api will be easier as "META-INF/services/javax.xml.bind.JAXBContextFactory" is new added provider in jaxb-runtime 2.3.3 as @andymc12  posted. I moved this issue to https://github.com/eclipse-ee4j/jaxb-ri/issues/1466. Feel free to close this issue.  There is issue in com.sun.xml.bind:jaxb-runtime 2.3.3 artifact.

**Comment by lukasj** [comment]
should work as expected now (with jaxb-ri 2.3.4/3.0.0-b01 from staging)
