### ISSUE TITLE
Jakarta XML Binding 3.0 Release Tasks

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jaxb-api#171]
The release has been approved by the EMO, please complete:
- [x] promote api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
- [x]  go through the merged jakarta.ee specification website page to verify all the links are valid.
- [x]  approve the compatibility request.
- [x]   The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
- [x]  merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
done already
