### ISSUE TITLE
Should JAXB 3.0's ModuleUtil be referring to "com.sun.xml.internal.bind.v2.ContextFactory" RI class?

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jaxb-api#172]
When pulling in the JAXB 3.0 implementation in Open Liberty, we ran into an issue where the ModuleUtil file still references the old `com.sun.xml.internal.bind.v2.ContextFactory` reference implementation (see https://github.com/eclipse-ee4j/jaxb-api/blob/b717e34080470d12dfdd2daf74c3100dddae7c2b/jaxb-api/src/main/java/jakarta/xml/bind/ModuleUtil.java#L37 ).  I believe that it should be referencing `org.glassfish.jaxb.runtime.v2.ContextFactory` instead.

If this was an oversight in the 3.0 release, I would be happy to update the classname in ModuleUtil.  In that case would it be possible to publish a 3.0.1 release that includes this change?  Thanks!

**Comment by Siedlerchr** [comment]
Yes, we are facing the same error in our project and then get the error:   [java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]

**Comment by lukasj** [comment]
fixed by #176
