### ISSUE TITLE
mapping of interface to XML schema

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#18]
The mapping of interfaces to an XML schema construct was only briefly
mentioned in the conference call both further discussion and
resolution are pending.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
>  The mapping of existing Java interfaces to schema constructs is not
supported. Since an existing class can implement multiple interfaces, there is
no obvious mapping of existing interfaces to XML schema constructs.
