### ISSUE TITLE
mapping of java.lang.Object

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#23]
I suggested the mapping of java.lang.Object to xs:anyType in the
context of type substitution. Keith Visco suggested that
java.lang.Object could also be mapped to xs:any.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
java.lang.Object is mapped to xs:anyType
