### ISSUE TITLE
Correct License?

### ISSUE THREAD

**Issue by hrieke** [eclipse-ee4j/jaxb-api#261]
Hi guys,

Could somebody please just double check to see if the licenses are correct here.
https://github.com/eclipse-ee4j/jaxb-api/blob/master/LICENSE.md
is BSD 3-Clause.

The Readme says:
https://github.com/eclipse-ee4j/jaxb-api/blob/master/README.md
Eclipse Distribution License (EDL) v1.0

The headers in the files say:

Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
This program and the accompanying materials are made available under the
terms of the Eclipse Distribution License v. 1.0, which is available at
http://www.eclipse.org/org/documents/edl-v10.php.
SPDX-License-Identifier: BSD-3-Clause

Manifest says:
Bundle-License: http://www.eclipse.org/org/documents/edl-v10.php

This isn't a trivial nitpick either, since I'd like to understand what my legal rights are and what my legal responsibilities will be if I use your code (and you might want to double check ALL projects under the eclipse-ee4j repo).
See also:  https://github.com/eclipse-ee4j/angus-activation/issues/9

Thank you,

**Comment by lukasj** [comment]
see https://www.eclipse.org/org/documents/edl-v10.php :

> The Eclipse Distribution License is an OSI Approved Open Source License by means of the [New BSD License](http://www.opensource.org/licenses/BSD-3-Clause).
