### ISSUE TITLE
mapping collection : java.util.Set -> XSD construct

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#27]
Issue raised by Ias.

java.util.Set is part of the Java Collection Framework; it
should be mapped to an XML schema construct.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
same rules as to _java.util.List_ are used for _java.util.Set_
