### ISSUE TITLE
mapping : adapting Java structures to XML representation

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#28]
Proposed by Dennis Sosonski

Dennis proposed an adapter approach for handling Java structures that
don't have a natural XML representation. This was originally proposed
in the context of HashMap but is not specific to mapping of HashMap.
See the email thread:

[http://archives.java.sun.com/cgi-bin/wa?A2=ind0402&L=jsr-222-eg&F=&S=&X=78A3F110158D3BF325&Y=sekhar.vajjhala@sun.com&P=173](http://archives.java.sun.com/cgi-bin/wa?A2=ind0402&L=jsr-222-eg&F=&S=&X=78A3F110158D3BF325&Y=sekhar.vajjhala@sun.com&P=173)

This was also discussed briefly at the F2F and thought to be useful by
JAXB 2.0 EG members present and deserved further investigation. See
bullet item 11 in the F2F minutes:

[https://jsr222.dev.java.net/files/documents/919/3776/f2f-minutes.txt](https://jsr222.dev.java.net/files/documents/919/3776/f2f-minutes.txt)
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
assuming this is fixed by the presence of XmlAdapter
