### ISSUE TITLE
XMLGregorianCalendar missing a schema-aware comparison function

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#3]
Submitted by David Bau, entered by Joe Fialli

There is no schema-aware comparison function on the
XmlGregorianCalendar type. This is useful for validation, but it requires a
four-state (not a three-state) return value, because there is a "not equal
to" result defined by schema.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
it is [there](https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/XMLGregorianCalendar.html#compare-javax.xml.datatype.XMLGregorianCalendar-)
