### ISSUE TITLE
Schemas with deep nesting is more common than we thought

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#31]
We've been seeing reports from users saying that they have to work with a schema
that has a very deep nested structure.

JAXB 1.0 produces the nested interfaces for such elements/types, and as a result
it produces names too long to be used. In fact, the complaints were that the
class file name becomes so long that it goes beyond the OS limit.

Currently, there's no workaround for this problem.
I wonder if the EG could consider this problem in JAXB 2.0.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[1.0]

**Comment by lukasj** [comment]
all generated classes/packages can be customized using a binding schema language
