### ISSUE TITLE
Unmarshaller StAX API clarification

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#33]
The new StAX APIs on javax.xml.bind.Unmarshaller need to specify that
START_DOCUMENT is a legal state for the XMLStreamReader or XMLEventReader
passed into the unmarshal() method.

The javadoc currently says that the methods throw IllegalStateException
for anything other than START_ELEMENT.
#### Environment
Operating System: All
Platform: All
URL: [https://jsr222.dev.java.net/nonav/api/javax/xml/bind/Unmarshaller.html](https://jsr222.dev.java.net/nonav/api/javax/xml/bind/Unmarshaller.html)
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
javadoc contains:

> This method assumes that the parser is on a START_DOCUMENT or START_ELEMENT event.
