### ISSUE TITLE
Bug in @XmlElement.name javadoc 

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#34]
> public @interface XmlElement {
> /**
> * Name of the XML Schema element. By default, the XML Schema
> * element name is derived from the JavaBean property name.
> *
> */
> String name() default "";

This customization might be used on a class, so just saying
"from the JavaBean property name" is inaccurate. You should say
something like:

... from (1) the JavaBean property name if the customization is
spcified on a method or a field and (2) the class name if the
customization is specified on a class.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
this is already clarified by "If the value is "##default", then element name is derived from the JavaBean property name"
