### ISSUE TITLE
XmlJTypeAdapter javadoc is sketchy

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#35]
The printMethod and the parseMethod should say exactly what is allowed.

As I understand it

*   "new" to invoke the constructor
*   just a method name (e.g., "toString") to invoke an instance method
*   a fully qualified method name (e.g., "abc.def.Ghi.jkl") to invoke a static
    method.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
XmlJavaTypeAdapter was redesigned
