### ISSUE TITLE
@XmlCollection.values should be "value"

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#36]
Otherwise people will be forced to write:

@XmlCollection(values=

{ @XmlCollectionItem(type=Ref4.class) })
List w;

Instead of :

@XmlCollection({ @XmlCollectionItem(type=Ref4.class) }

)
List w;
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
@XmlCollection was removed
