### ISSUE TITLE
@XmlValue too restrictive

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#37]
The clause "@XmlValue must be the only mapping annotation on the JavaBean
property" in javadoc is too strong. You should be able to use other annotations,
such as XmlID, XmlIDREF, or XmlJavaTypeAdapter.

This phrase should be modified to "@XmlValue, @XmlAttribute, and @XmlElement are
mutually exclusive and may not be on one property at the same time"
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
looks to be fixed
