### ISSUE TITLE
XmlElement.isNillable name inconsistency

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#38]
It is customary for annotation parameters not to accompany a verb.
For example, you don't name it "getValue", but you name it "value".
You don't name it "getName", but you name it "name".

Most of the JAXB annotations follow this convention correctly,
yet "isNillable" is not. This should be renamed to "nillable" for
consistency.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
fixed
