### ISSUE TITLE
mapping - default mapping of class is incorrect

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#39]
In the JAXB 2.0 ED 0.40, the default mapping of class is xs:all. It should be
xs:sequence; this has already been agreed to earlier in the JAXB 2.0 EG.
The specific error is:

Error: Section 8.8.1.1, "Synopsis" reads

public @interface XmlType {
String name();
String[] propOrder() default {}; ***** incorrect default *****
String targetNamespace() default "##default" ;
}

However it should read

public @interface XmlType {
String name();
String[] propOrder() default ""; ****** correct default ******
String targetNamespace() default "##default" ;

With the above change, the class would be mapped to xs:sequence
(see table, 8-5, "Mapping: Class body to Model Group Component").

Note: The above bug does not exist in the javadoc for
the javax.xml.bind.annotation.XmlType annotation.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
apparently fixed already
