### ISSUE TITLE
XMLGregorianCalendar parsing enhancements

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#4]
Submitted by David Bau, entered initially by Joe Fialli

Rather than having eight separate parsing functions, (for all of the g*, date,
dateTime
datatypes), there simply should be one parsing function that can accept all the
forms
(with any of the five subfields Y/M/D/time/timezone omitted); this is simple
to implement; it would be a simpler API; it is a nice solution for unions;
and validators could use a getXmlSchemaType() method to verify that the
proper form were loaded.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
[there](https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/DatatypeFactory.html#newXMLGregorianCalendar-java.lang.String-) seems to be exactly one parsing method
