### ISSUE TITLE
DatatypeConverter / DatatypeConverterInterface are underspecified

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#42]
It doesn't say what happens in case of an error. Does it throw an exception?
Does it just return null?
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
> If an error is encountered during conversion, then an IllegalArgumentException, or a subclass of IllegalArgumentException must be thrown by the method.
