### ISSUE TITLE
Unmarshaller.unmarshal method that takes java.io.Reader

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#43]
XML can be read from java.io.Reader, and often people do that, yet the
javax.xml.bind.Unmarshaller interface doesn't have a version that takes
java.io.Reader.

This is a strange omission given that the Marshaller has a version of the
marshal method that takes java.io.Writer.

Currently the user can work around this problem by:

unmarshaller.unmarshal(new StreamSource(reader));
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
Reader is there
