### ISSUE TITLE
mapping: @XmlType.name() inconsistent in javadoc and spec

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#44]
The javadoc and specification in Chapter 8 are inconsistent in the
treatment of the @XmlType.name() annotation parameter. The references
to chapter 8 below are from JAXB 2.0 v0.42.

a. The javadoc indicates @XmlType.name() is required.
but the default mapping in section 8.8.1.3 omits it.

b. The mapping tables 8-4 (which maps a class to a complex type) and
8-6 (which maps a class to a simple type) allow @XmlType.name() to be "".
But the javadoc does not define the semantics when @XmlType.name() is "".
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 v0.4]

**Comment by lukasj** [comment]
I believe this is fixed
