### ISSUE TITLE
XMLGregorianCalendar years & seconds precision

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#5]
Submitted by David Bau, entered initially by Joe Fialli.

Concerning javax.xml.datatypes.XMLGregorianCalendar:

To permit correct behavior on validation tests, it is important that, like
Duration, the calendar type be able to handle large years and more than
three digits of fractional seconds; it would also be optimal if the number
of significant digits of seconds were remembered, so that dates can be
nicely round-tripped to XML. I recommend that this information be able to
be held by the XmlGregorianCalendar implmentation and accessible by its own
API, but truncated when queried by the ordinary Calendar API.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
this seems to be already there
