### ISSUE TITLE
XMLGregorianCalendar needs a getXmlSchemaType() method

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#6]
Submitted by David Bau, entered initially by Joe Fialli

There should be a method to say "which one of the XML Schema Date
types does this correspond to"? based on the set fields, e.g., have an
enumeration for gYear, gMonth, gMonthYear, as well as no-type, and then have
a getXmlSchemaType() method. What's the use case? We have some customers
with schemas where they have unions of various XML Schema Date types, and it
is very useful to know which member of the union they have.
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
it is [there](https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/XMLGregorianCalendar.html#getXMLSchemaType--)
