### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-api#63]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by Tomas-Kraus** [comment]
Jobs:
- master branch: https://jenkins.eclipse.org/jaxws/job/saaj-api-master-build/
- EE4J_8 branch: https://jenkins.eclipse.org/jaxb/job/jaxb-api-ee4j8-build/
Both are passing.
