### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-api#64]
We need to create a release CI/CD pipeline for this project. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by Tomas-Kraus** [comment]
Blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=538891

**Comment by Tomas-Kraus** [comment]
Job: https://jenkins.eclipse.org/jaxb/job/jaxb-api-release/
tested with master and EE4J_8 branches.
