### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-api#72]
- [x] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by Tomas-Kraus** [comment]
Prepared https://github.com/eclipse-ee4j/jaxb-api/pull/73 for master branch. Identical change will go into EE4J_8 too.
We are blocked by jakarta.activation release.

**Comment by m0mus** [comment]
Done
https://oss.sonatype.org/content/groups/staging/jakarta/xml/bind/jaxb-api/2.3.2/
