### ISSUE TITLE
add XMLGregorianCalendar.add(Duration)

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-api#9]
Add a method to javax.xml.datatype.XMLGregorianCalendar that adds a Duration to
XMLGregorianCalendar.

Duration.addTo(java.util.Calendar) and Duration.addTo(java.util.Date) already
provide
a means to add a duration to these object. Add the logical equivalent of adding
duration to XMLGregorianCalendar, XMLGregorianCalendar.addTo(Duration).
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.0 draft]

**Comment by lukasj** [comment]
it is [there](https://docs.oracle.com/javase/8/docs/api/javax/xml/datatype/XMLGregorianCalendar.html#add-javax.xml.datatype.Duration-)
