### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-api#90]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
JAXB was released: https://jenkins.eclipse.org/jaxb/job/jaxb-api-close/27/console
Created PR to merge release info into EE4J_8: https://github.com/eclipse-ee4j/jaxb-api/pull/91
