### ISSUE TITLE
Update Scope Statement for Jakarta XML Binding Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaxb-api#94]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by waynebeaton** [comment]
How about this?

> Jakarta XML Binding defines an API and tools that automate the mapping between XML documents and Java objects.

**Comment by waynebeaton** [comment]
I'm going to take the following to the Specification Committee for approval:

> Jakarta XML Binding defines an API and tools that automate the mapping between XML documents and Java objects.
