### ISSUE TITLE
Change project name to Jakarta XML Binding

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jaxb-api#95]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
Any objections to the name "Jakarta XML Binding"?

**Comment by m0mus** [comment]
No objections

**Comment by bravehorsie** [comment]
"Jakarta XML Binding" looks good to me.
