### ISSUE TITLE
Jakarta EE 8 TCK job

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jaxb-api#96]
To test Jakarta EE 8 compatibility we need to create a Jenkins job on project's Cloud Jenkins instance formally testing the API against the relevant TCK and as needed, relevant CTS subset tests. 

For projects that do not already have automated testing, there is provided parameterized Jenkins job that can be invoked to perform these tests. User provides a link to an Eclipse GlassFish test build and sets the test sub-set parameters:

- For CTS -- https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
- For Stand-alone TCKs -- https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

Additional instructions and guidance for using and directly running TCKs is available on [this wiki](https://wiki.eclipse.org/TCK:Build_From_Jakarta_EE_TCK_Repo_And_Run). Also in the [jakartaee-tck](https://github.com/eclipse-ee4j/jakartaee-tck) project repository.

**Comment by Tomas-Kraus** [comment]
I'm not commiter in jakartaee-tck project and my account does nit have right to edit jobs on https://ci.eclipse.org/jakartaee-tck/
I can setup JAXB/Metro related jobs in jaxb or metro projects (https://ci.eclipse.org/jaxb or https://ci.eclipse.org/metro)

**Comment by Tomas-Kraus** [comment]
Currently whole jakartaee-tck project in master branch is not buildable because of javax -> jakarta changes being in progress.
I fixed SAAJ and added https://ci.eclipse.org/metro/job/saaj-tck-build/ job to have access to the binaries.

**Comment by lukasj** [comment]
@Tomas-Kraus from when is jaxb-tck part of jakartaee tck? I thought it's standalone TCK living in its own [repository](https://github.com/eclipse-ee4j/jaxb-tck). Who did set up [this job](https://ci.eclipse.org/jaxb-impl/job/jaxb-ri-tck/)? Isn't it what was required to be done?

**Comment by Tomas-Kraus** [comment]
Well, I misunderstand this task a bit. JAXB TCK job for Jakarta EE 8 compatibility exists since June 2019 and works fine.
https://ci.eclipse.org/jaxb-impl/job/jaxb-ri-tck/
